### ISSUE TITLE
Label and URI in dropdown menu exceeds width of Item form

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/CustomVocab#20] opened 2021-06-21 16:09 UTC
Pushes the delete value icons out of reach.

There might need to be a forced wrap of the URI?

**Comment by jimsafley** [comment] 2021-06-21 16:21
I can't reproduce this. Could you post a screenshot? 
![image](https://user-images.githubusercontent.com/141955/122795304-2ea84980-d28b-11eb-8b21-cedb19684930.png)

**Comment by sharonmleon** [comment] 2021-06-21 16:25
It's after the selection has been made. So when you go back to edit.

![Screenshot 2021-06-21 at 12-23-47 Edit · Sharon Leon Test Item · Items · SML Omeka S Test](https://user-images.githubusercontent.com/741480/122795815-b4c49000-d28b-11eb-8924-68db40c3d59c.png)

**Comment by sharonmleon** [comment] 2021-06-21 16:36
Here's a better screenshot of the form in edit mode (after vocab selections have initially been saved/created).

![Screenshot 2021-06-21 at 12-34-39 Edit · Sharon Leon Test Item · Items · SML Omeka S Test](https://user-images.githubusercontent.com/741480/122797095-1b967900-d28d-11eb-8d16-5e35660d6f5c.png)

**Comment by sharonmleon** [comment] 2021-06-21 18:43
This seems to be an issue with the responsiveness of the form.

**Comment by jimsafley** [comment] 2021-06-21 22:02
Fixed in core https://github.com/omeka/omeka-s/commit/da7b5de78f51524014d0b3b67fe8ad6bb59a5fe6. I'm upping the version constraint of this module to 3.1.0.

**Closed by jimsafley** 2021-06-21 22:02 UTC
